export const environment = {
  production: false,
  epRaiz: 'http://localhost:4001',
  epLogin: '/login',
  epRegistrarUsuario: '/registerUser',
  epValidarRegistroUsuario: '/validateRegisterUser',
  epValidarExisteUsuario: '/validateExistsUser',
  epRegistroEmpresa: '/registerCompany',
  epListarEmpPorUsu:'/getCompanyByIdUser'  ,
  epRegistrarEmpleo: '/registerJob',
  epListarEmpleosPorUsu:'/getJobsByIdUser',
  epImagesPublic: 'http://localhost:4001/public',
  epActualizarReclutador: '/updateDataUser',
  epListarReclutadorPorId:'/getRecruiterById',
  epActPwdReclutador: '/updatePasswordAccount',
  epListarEmpleosOpenClose: '/getJobsOpenClose',
  epEliminarEmpleosPorIds: '/deleteJobsByIds',
  epValidaTokenGoogle: '/validateTokenGoogle',
};
