export const environment = {
  production: true,
  epRaiz: 'https://dev-laboral-back.azurewebsites.net',
  epLogin: '/login',
  epRegistrarUsuario: '/registerUser',
  epValidarRegistroUsuario: '/validateRegisterUser',
  epValidarExisteUsuario: '/validateExistsUser',
  epRegistroEmpresa: '/registerCompany',
  epListarEmpPorUsu: '/getCompanyByIdUser',
  epRegistrarEmpleo: '/registerJob',
  epListarEmpleosPorUsu: '/getJobsByIdUser',
  epImagesPublic: 'https://dev-laboral-back.azurewebsites.net/public',
  epActualizarReclutador: '/updateDataUser',
  epListarReclutadorPorId: '/getRecruiterById',
  epActPwdReclutador: '/updatePasswordAccount',
  epListarEmpleosOpenClose: '/getJobsOpenClose',
  epEliminarEmpleosPorIds: '/deleteJobsByIds',

  epValidaTokenGoogle: '/validateTokenGoogle',
};
